### ISSUE TITLE
gradle-pluginをマルチプロジェクトで実行した場合のファイルを分ける

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#105]
マルチプロジェクトで一律に実行した場合、デフォルトだと同名ファイルが作成され、最後のプロジェクトの結果しか残らない。
デフォルトのファイル名をプロジェクトごとに変えるとかしておきたい。

**Comment by haljik** [comment]
出力先ディレクトリをルートプロジェクト（jig-gradle-pluginを適用したプロジェクト）毎にしました。
