### ISSUE TITLE
gradle-pluginをマルチプロジェクトで実行した場合に集約した結果を見たい

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#106]
マルチプロジェクトに適用した場合も個々のプロジェクトに実施することになるため、個別にダイアグラムは出力される。
サブプロジェクトを包括しての出力をしたいところ。

**Comment by haljik** [comment]
10d41e9e9d4587cabade6fc7e7bc6d99c7556f41 で包括出力に対応
