### ISSUE TITLE
記法について警告メッセージ

### ISSUE THREAD

**Issue by masuda220** [dddjava/Jig#107]
基本的な書き方が、Jigの想定に適合していない場合に、警告を出力する
（Jig の new comer に優しく）

- `@Service` が見つからない
- /domain/model が見つからない (実行オプションで指定がない場合)

**Comment by irof** [comment]
https://github.com/dddjava/Jig/wiki/HELP に記載するような内容。

それぞれの検出タイミングで独自例外を送出し、通常の実行ログとは別に目立つログを出力するイメージ。

**Comment by irof** [comment]
![2018-05-30 15 27 40](https://user-images.githubusercontent.com/615346/40702885-7933fd48-641e-11e8-8574-2ce988b9ddc2.png)
