### ISSUE TITLE
--jig.model.pattern を指定した時も、冗長なパッケージ名をカットする

### ISSUE THREAD

**Issue by masuda220** [dddjava/jig#119]
--jig.model.pattern でパターンを指定した時に、パッケージ依存図で、冗長な上位のパッケージ名が表示される。
表示を抑止したい。

他のレポートでも同様かは、未確認。

**Comment by irof** [comment]
モデル判定パターンと、出力抑止パターンは別の設定になっています。
抑止したいパターンを `output.omit.prefix` で指定してください

たとえば `--output.omit.prefix=com\\.example\\.model\\.`

https://github.com/dddjava/Jig/wiki/HELP/_edit#%E5%86%97%E9%95%B7%E3%81%AA%E5%87%BA%E5%8A%9B%E3%82%92%E6%8A%91%E6%AD%A2%E3%81%97%E3%81%9F%E3%81%84%E8%AA%BF%E6%95%B4%E3%81%97%E3%81%9F%E3%81%84

設定を階層化すればある程度一本化はできるかもしれませんが・・・

**Comment by irof** [comment]
パッケージ関連図の上位階層グルーピングで冗長感はほぼなくなってるかなと思います。
必要であれば別途。
