### ISSUE TITLE
メソッドの利用箇所がメソッド以外である場合に検出が漏れる

### ISSUE THREAD

**Issue by haljik** [dddjava/Jig#121]

**Comment by irof** [comment]
domain.xlsxの「真偽値を返すメソッド」の使用箇所。

**Comment by irof** [comment]
https://github.com/dddjava/Jig/blob/510817c1c8c0bd5e82cb2f8ef4310ef3a8bb09a4/jig-core/src/main/java/org/dddjava/jig/domain/model/implementation/bytecode/MethodRelations.java#L23

MethodRelationをインスタンスメソッドを軸でしか作ってないから。

**Comment by irof** [comment]
MethodRelationがstaticメソッド、コンストラクタ、lambdaを扱うようになったので、「文字列比較箇所」にが出るようになった。出ていい。
