### ISSUE TITLE
ビジネスルール一覧に出るクラスをモデルだけにする

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#128]
モデル≒domainパッケージ配下。

現状だと、条件にあえば（コレクションである、とか。）どのパッケージにあっても（infrastructureとか）一覧に出力されるので。

**Comment by haljik** [comment]
f395e05 で対応しました。

**Comment by haljik** [comment]
https://github.com/dddjava/Jig/issues/175 でRevert しました
