### ISSUE TITLE
enumの定数宣言にenumの列挙以外が出力される

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#129]
staticフィールドを出力しているため、列挙以外でもenumにstaticフィールドがあると出力されてしまう。
enumにstaticフィールドがあるのもどうよってのはあるが・・・それはそれとして。

enumの型の定数宣言だけにする。

**Comment by haljik** [comment]
解消してます

**Comment by haljik** [comment]
一旦Revertして再現テスト込で対応する
