### ISSUE TITLE
パッケージ依存関係図で出力されない関連がある

### ISSUE THREAD

**Issue by haljik** [dddjava/Jig#138]
少なくとも今わかっているのは次の関連
- static final なプリミティブフィールドへの参照

**Comment by irof** [comment]
この手の不具合再現テストは「これが落ちるべきだけど通ってしまう」という感じでmasterに入れちゃっていいと思います。

ところで。
 "stub.domain.model.relation.staticmethodinstruction -> stub.domain.model.relation.field"
これに該当するのってどれになります？

https://github.com/dddjava/Jig/blob/test-static-method-to-static-field-package-dependencies/jig-core/src/test/java/stub/domain/model/relation/staticmethodinstruction/StaticMethodInstruction.java#L24
かと思ったけれど、これは `stub.domain.model.relation.method` ですし・・・

**Comment by haljik** [comment]
> この手の不具合再現テストは「これが落ちるべきだけど通ってしまう」という感じでmasterに入れちゃっていいと思います。
👍 

> "stub.domain.model.relation.staticmethodinstruction -> stub.domain.model.relation.field"
これに該当するのってどれになります？

読み違えてますね。テストし直します。

**Comment by haljik** [comment]
static fieldじゃなくて、static final Stringに対する参照ですね。
byteCodeじゃ厳しいのかもしれない
