### ISSUE TITLE
onejar版で処理時間が長くなる

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#156]
Jigに対する処理時間
- SpringBoot: 8677 ms
- onejar: 27816 ms

入出力リストの出力に特に時間がかかっている（この際にJavaの別プロセスが立ち上がる？）

**Comment by haljik** [comment]
onejar版で、jarを統合するpluginを `https://github.com/johnrengelman/shadow` に変更。
処理時間は  6236 ms に。

うまく動くが依存Jarが展開されて格納されてしまうところが気になる。

**Comment by irof** [comment]
ああ、クラス舐めるのにjarの中を走査してたから遅かったのかな。

**Comment by irof** [comment]
ライセンスファイルが気になるところ。

**Comment by haljik** [comment]
ライセンスファイルはすべてのJar(Jigの分を含めて)zipで固められていて
zipがネストしているようでunzipしようとするとライセンスを上書きするか尋ねられます。
これがどんな問題になるのかわかってないですね。。。

**Comment by irof** [comment]
これは同じファイル名（大文字小文字違い）で上書きするか聞かれてる系ですね。zip内は区別される。
なので同じファイル名（大文字小文字も同じ）は1つしかなさそう。

使用してるライブラリごとにLICENSEファイル分けて含めたいなぁ。
使用してるライセンスのLICENSEファイルを一通り置いといて対応リストも含めておく、とかでもよさそうですが。

**Comment by haljik** [comment]
ああ。なるほど。。。
ライセンスファイルを集めて分けて配置するようなタスクつくればいけそうかな。

**Comment by irof** [comment]
配置場所がまちまちなので結局個別対応になりそうですよね・・・。

wikiに書いてる[これ](https://github.com/dddjava/Jig/wiki#%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA) をソースに置くって意味で、gradleタスクじゃなく手動管理でもいいかもしれない。

とはいえ二重管理になるので、同じような情報がそれなりに読みやすいgradleスクリプトで書けて、それを `build.gradle` から呼び出す形になるならその方が好ましいかも。

**Comment by irof** [comment]
#150 取り下げに伴い。
