### ISSUE TITLE
ディレクトリ作成に失敗してファイル出力ができない

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#157]
gradle pluginでdaemonが立ち上がっている場合に起こる。
相対パスの解釈がAPIによって変わる？

`Files#createDirectories` で意図しない場所（daemonが立ち上がった場所？）にディレクトリが作成されてしまう。
https://github.com/dddjava/Jig/blob/d29360c6634b735414487a7a2dbe6abb557e3b64/jig-core/src/main/java/org/dddjava/jig/presentation/view/handler/JigDocumentHandlers.java#L64-L67

以降の `JigDocumentWriter` などでは意図通りのファイルパスに出力しようとする。
https://github.com/dddjava/Jig/blob/d29360c6634b735414487a7a2dbe6abb557e3b64/jig-core/src/main/java/org/dddjava/jig/presentation/view/JigDocumentWriter.java#L35

結果、ディレクトリがないのでエラーとなる・・・。

```
> Task :jig-core:jigReports FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jig-core:jigReports'.
> java.nio.file.NoSuchFileException: build/jig/jig-core/service-method-call-hierarchy.svg
```

**Comment by haljik** [comment]
b9c7534 で修正しました。
