### ISSUE TITLE
GradlePluginで警告終了の場合に何も出力されない

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#190]
`--info` とかつければ出るのだけど。

**Comment by haljik** [comment]
e743103 で修正できたが、根本原因まではつかめていない。
ログ出力にTaskがもっているgetLogger()を使うと出力されるようになる。
タスク内で直接出力しているログについてはquietで出力するので当然出るようになるのはわかるが、
core内部で出力している警告メッセージについてもこれで出力されるようになる。
使われるロギングライブラリが変わるように見える

**Comment by irof** [comment]
問題なく出力されてるのでclose
