### ISSUE TITLE
マルチプロジェクトのサブプロジェクト横断に対応

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#199]
```
[root]
+-- api-module
+-- domain-module
```

みたいな構成だと、現状は api-module, domain-module 単位の出力になる。
api-module -> domain-module な参照関係の場合、相互の関連がとれないと参照箇所などがイマイチ使えないものになってしまう。

gralde pluginはビルドディレクトリなどが解決できることなので、その利点を失わずに対応できるかが焦点。

**Comment by haljik** [comment]
api-moduleに定義したらdomain-moduleを含んだ出力になりませんか？

**Comment by irof** [comment]
いけました！domain-moduleの方で出してダメかと思いました。
api-moduleでいけるなら問題ないかなと思います。
（複数apiまたがりはできない、というかそれがしたければ全サブプロジェクトに依存したjig用プロジェクトを1つつくればいいかな・・・）

pluginの適用対象のガイドをWIKIかREADMEでフォローすることにします。
