### ISSUE TITLE
複数のソースディレクトリを指定できるようにする

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#207]
ソースディレクトリが複数ある場合、 `directory.sources` に指定した一つのディレクトリのJavaファイルしか読み込まれない。

gradle pluginも？

**Comment by acro-skawakami** [comment]
> gradle pluginも？

gradle pluginも。

**Comment by haljik** [comment]
> gradle pluginも？

gradle pluginも。
だけど、基本的にJavaプラグインのディレクトリ規約で、src/mainがメインソースセットなのでそこだになります。

**Comment by irof** [comment]
まずは本体で複数指定できるように対応。
gradle pluginに関しては、ソースディレクトリの追加をbuild.gradleに書いてたら、それから取得する・・・って感じかな

**Comment by haljik** [comment]
gralle pluginに関してはLayoutインタフェースの実装を差し替えて動いているので本体の対応に影響しないため先に対応しました。

**Comment by haljik** [comment]
テストのメインソースセットは省いたものの。他にテスト用のソースセット定義されたら出てきてしまうという問題がある。。。

**Comment by irof** [comment]
GradlePluginでできてるので問題ない。
CLIは上位ディレクトリでやればいいや感がある。
