### ISSUE TITLE
パッケージ関連図を上位パッケージでグルーピングする

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#275]
サブパッケージになってても関係なく個別に扱っている。

上位パッケージで subgraph をつける。とりあえず目立たない感じで、位置だけ近くなったりすればよい。

**Comment by masuda220** [comment]
お！
なんか良さげ。

**Comment by irof** [comment]
<img width="539" alt="スクリーンショット 2019-05-13 15 46 58" src="https://user-images.githubusercontent.com/615346/57601042-76315700-7596-11e9-9af2-323683ef7b21.png">
