### ISSUE TITLE
Kotlinの別名サポート

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#288]
Kotlinの別名を扱えるようにする。

- [x] #287 を `kotlin` ブランチに取り込む
- [x] Kotlin向けのリリース
    - バージョン `2019.5.4-kotlin` とか？
- [x] [isolating-the-domain](https://github.com/system-sekkei/isolating-the-domain) のような想定プロジェクトを見つけるか作る。
    - https://github.com/irof/kotlin-spring-mvc
- [x] `SourceCode` を `master` で扱えるようにする。
    -  `master` ブランチでやって `kotlin` ブランチにマージする。
    - インタフェースの実装じゃなくenumとPOJOにしたい。
    - JIGドキュメント（パッケージ関連図）でソースコードとはJavaとKotlinを扱っているのがわかるようにしたい。
    - *変更を最小にするためのリファクタリング*
- [x] `master` ブランチに統合
    - *アクティブメインライン* への合流。
    - Kotlinコンパイラはオプションとしたい。
        - gradleプラグインはいいとして、cliは・・・実行時解決？

# メモ
- Kotlinコンパイラを取り込むとjarサイズが大きくなってしまう
    - jig-cli: 33MB -> 70MB

# 参考

*斜体* は https://github.com/dddjava/Jig/wiki/DEV_PATTERN

**Comment by masuda220** [comment]
暫定的にKotlin ブランチを作って、そちらも並行してリリースする、に賛成です。

masterへのマージは反対です。
Kotlin対応のために、Jigの開発の柔軟性やスピードを低下させたくないし、jarサイズが膨らんだりするのは、本来の開発意図からはずれます。

将来的には、共有カーネル＋共有サブドメイン群　があって、それをJava用に利用、Kotlin用に利用、というような形態が望ましいと思っています。
そういう方向を目指して、全体の構造を改善していくことは、望ましい方向だと思っています。

ただし、それには時間がかかるし、何か変更するたびに、Kotlinブランチに適応する、というのも、負担が大きすぎる。（Jigの進化のスピードを落とす）

ですので、基本的には
- 現時点での Kotlinブランチは、そのまま完全に切り離して、masterの変更を反映しない
- master側の変更の様子を見ながら、ある段階で、再度、新バージョンの Kotlin ブランチを作る
ということを繰り返す、というやり方が良いと思います。
これを繰り返しながら、さきほどの　共有カーネル、共有サブドメインを段階的に発見・充実させていく、というアプローチです。

**Comment by masuda220** [comment]
kotlinブランチをサポートするメンバーが、随時、マスターの変更を取り込むのはありだとは思います。

**Comment by irof** [comment]
> 将来的には、共有カーネル＋共有サブドメイン群　があって、それをJava用に利用、Kotlin用に利用、というような形態が望ましいと思っています。
そういう方向を目指して、全体の構造を改善していくことは、望ましい方向だと思っています。

基本的にこの方向です。
Kotlin対応によって特に `implementation.raw` 周りがいい感じに揺れたので、とりあえずパッケージ分割からやってます。

> jarサイズ

今でも大きい認識なので、標準で取り込んだものにはならない形にはするつもり。
