### ISSUE TITLE
Q. branches.xlsx：if文がないコードでも「分岐数」が出るのは期待通りの動作？

### ISSUE THREAD

**Issue by kbtaniguchi** [dddjava/Jig#319]
1for文=2branchとカウントされているように見える

**Comment by irof** [comment]
動作としてforが検出されるのは想定通りです。 #65
例えば拡張for文はコレクションや配列のイテレーションによる判定がコードの記述箇所で行われています。
分岐数の出力目的は、判断のビジネスルール外の流出を検知するこのですので、出力対象としています。

2分岐とカウントされているのは以下のように2箇所ジャンプしているためです。

```
1: for (/* ループ条件 */) {  // => ループ条件を判定して満たさなかったら4にジャンプ
2:     /* 何らかの処理 */
3: }  // => 1にジャンプ
4: /* 後続処理 */
```

改善対処だとは思います。 #320

**Comment by kbtaniguchi** [comment]
なるほど、納得しました。ありがとうございます。

**Comment by kbtaniguchi** [comment]
単純な質問だったのでクローズしてしまいます
