### ISSUE TITLE
application.xlsxの「SERVICE」シートの「メソッド別名」項目の出力内容が正しく無いように見える

### ISSUE THREAD

**Issue by kbtaniguchi** [dddjava/Jig#361]
## 不具合の内容
application.xlsxの「SERVICE」シートで、「同一サービス内で引数・戻り値違いの同名メソッド」の「メソッド別名」がどちらか一方に寄って出力されており、正しくないように思えます。

例えば以下のようなサービスクラスがある場合に、
```
@Service
public class XxxxxQueryService {

    /**
     * Xxxxxを取得
     */
    public Xxxxx get(XxxxxNumber number) {
        ....
    }

    /**
     * Xxxxxサマリを取得
     */
    public XxxxxSummary get(XxxxxNumber number, Yyyyy y) {
        ....
    }
```
レポート上に出る２行の「メソッド別名」が両方とも「Xxxxxを取得」になってしまう、という事象です。（そもそもメソッド名の付け方それでいいの？とか、別サービスに分けるべきでは？というのはひとまず横に置いておいてください。。。）

## 環境
- JIGのバージョン: 2019.8.3
- 実行方法: jig-gradle-plugin
- Javaのバージョン: 11.0.1-open
- OS: macOS Mojave 10.14.6

**Comment by irof** [comment]
JIGとしては横に置いておいておけなくのではなく、メソッド名の変更が妥当で対応していないものになります。 参考 #98

とは言えなんの案内もないのは問題とは認識。
オーバーロードに対応するか、オーバーロードされていることを警告ログするか、いずれかの対応はしようと思います。

**Comment by kbtaniguchi** [comment]
承知しました。ありがとうございます。ではこちらのissueはcloseしてしまいます。
