### ISSUE TITLE
Springの@Componentのvalue属性を日本語名として使う

### ISSUE THREAD

**Issue by masuda220** [dddjava/jig#373]
日本語名（別名）の情報源として、Sprint Frameworkの ```@Component``` の `value属性` の値を、JavaDoc形式の記述より優先して表示したい

```@Component, @Controller, @Service, @Repository``` の `value属性` に日本語名を使うことを推奨したい。

- JavaDoc形式よりも、そのコンポーネントの名称として読みやすくなる
- クラス名が他のパッケージのクラス名と重複しても、value属性で一意識別ができる
- 結果として、クラス名を（重複の心配せずに）単純な名前にできる
- コンポーネントのvalue属性というコンパイラが認識する情報として記述するほうが、コードから意図を読み取るツール向けの記法として、優れている

**Comment by irof** [comment]
Springで `@Component("注文明細")` などは違和感が強く、また名称の重複時のコンパイルチェックが効かない（実行時例外になる）ので採用しません。
