### ISSUE TITLE
ユースケース複合図のtooltipを表示をクラス名/メソッド名のみに

### ISSUE THREAD

**Issue by masuda220** [dddjava/jig#469]
ユースケース複合図でマウスオーバーした時に表示する内容を、クラス名より前のパス情報を表示しない。

* サービスクラスのメソッドは、クラス名＋メソッド名のみ
* サービスクラスのメソッドの引数は、クラス名のみ
* コントローラクラス、ドメインクラスは、クラス名のみ

**Comment by irof** [comment]
次回リリースに入ります。
