### ISSUE TITLE
区分使用図の参照関係をサービスクラスのメソッドまでたどってほしい

### ISSUE THREAD

**Issue by masuda220** [dddjava/jig#470]
区分使用図で、直接使用するクラスだけでなく、そのクラスを参照する階層を表示してほしい。
サービスクラスのメソッドまで。
（ビジネスルールの区分の仕様範囲、変更時の影響範囲を確認しやすくするため）

**Comment by irof** [comment]
b41c7024f1d5b672070898ec624158eea4228980, cc3949077741797eb4f2ae8eb6b5d52e81e382a2

`2020.3.4.3` 以降で対応しています。
