### ISSUE TITLE
ロゴが欲しい

### ISSUE THREAD

**Issue by irof** [dddjava/jig#478]
何か欲しい。

## キーワード
木、鉄、工具、職人、モデリング、Java、コード、一時的なドキュメント、フィードバックループ、IDE、、、、

**Comment by irof** [comment]
![JIG](https://user-images.githubusercontent.com/615346/79400348-f0493780-7fc0-11ea-88a0-fb783975b32e.png)

仮。。

**Comment by tango238** [comment]
JavaというかDukeっぽいロゴ
<img width="97" alt="logo@2x" src="https://user-images.githubusercontent.com/123510/79476891-85414480-8044-11ea-9aa5-59eb67a41d3b.png">

**Comment by tango238** [comment]
シャープさ追加した
<img width="96" alt="logo2@2x" src="https://user-images.githubusercontent.com/123510/79479230-6d1ef480-8047-11ea-86e4-bbef1688133d.png">

**Comment by tango238** [comment]
JISっぽいやつ
<img width="125" alt="アセット 20@2x" src="https://user-images.githubusercontent.com/123510/79550673-a604ab00-80d3-11ea-849c-9ca9f92785aa.png">

**Comment by irof** [comment]
ループ、接着剤、グル……
