### ISSUE TITLE
区分使用図：他のドメインオブジェクトから参照されない区分の扱い

### ISSUE THREAD

**Issue by masuda220** [dddjava/jig#512]
区分オブジェクトを、サービスクラスのメソッドが使うだけの場合、区分使用図で、区分オブジェクトとサービスの関係が表示されない。

区分オブジェクトを利用するサービスクラスのメソッドと関係づけて表示させたい。
（現在の仕様では、右側に孤立した状態で表示される）

**Comment by irof** [comment]
これは出なきゃですね

**Comment by irof** [comment]
`2020.5.5` 対応済み。
