### ISSUE TITLE
ビジネスルール一覧のallシートに参照関係の情報を追加する

### ISSUE THREAD

**Issue by masuda220** [dddjava/jig#527]
* そのクラスを参照しているクラス数（被参照数）
* そのクラスが参照している他のクラス数
* パッケージプライベートのクラスか（パッケージプライベートだったら〇）

用途としては、リファクタリングをしたほうがよさそうなクラスの発見。

例えば、

*  被参照数が多すぎる
*  被参照が１なのにパッケージプライベートではない
* 他のクラスへの参照が多すぎる

などを見つけやすくしたい

**Comment by irof** [comment]
そのクラスを参照しているクラス数（被参照数）
`使用箇所数` `ビジネスルール使用箇所数` を追加しました。
同数であればビジネスルールからのみ使用されているもの、異なるものは三層から使用されているものです。

> そのクラスが参照している他のクラス数
`参照ビジネスルール数` を追加しました。
単純に参照しているクラス数だとJava標準ライブラリを含むため、ビジネスルールに限定しました。
三層への参照はアーキテクチャ図で検出する方向で。

> パッケージプライベートのクラスか（パッケージプライベートだったら〇）
`非PUBLIC`を追加しました。
これは `*.java` でなく `*.class` を参照していることによる制約で、 `protected` と`private` が区別がつかず、「パッケージプライベート」と言うと嘘になりえるので……（とは言えこれらのクラスはあまり作らないと思いますが）

参考: https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.1-200-E.1

上記とは別にパッケージプライベートの候補として `同パッケージからのみ参照` を追加しました。「被参照3だけれどパッケージプライベートにできるもの」が見つけづらかったので。

![image](https://user-images.githubusercontent.com/615346/84788589-3efb6800-b02a-11ea-83e8-aa9c902dfb82.png)

本対応は `2020.6.2.1` でリリースしました。
