### ISSUE TITLE
2020.11.2.1 index.html の改善要望

### ISSUE THREAD

**Issue by masuda220** [dddjava/jig#596]
①左側のツリーでパッケージを選択した時

右側は、選択したパッケージの説明と、そのパッケージ直下のクラス/パッケージの一覧を表示したい

現在は、先頭（選択されたパッケージ）以下に何が表示されているか、意図が不明。

②左側のツリーは、開閉式にしたい

**Comment by irof** [comment]
パッケージクリック時、右側はパッケージと説明のみを出力していましたが、
そのパッケージに含まれるパッケージと型のテーブルを出力するようにしました。

開閉は一旦見送りで。

**Comment by irof** [comment]
https://github.com/dddjava/jig/releases/tag/2020.12.4 以降、開閉もするようになってます。
