### ISSUE TITLE
拡張：ビジネスルール系とそれ以外の情報の分離

### ISSUE THREAD

**Issue by masuda220** [dddjava/Jig#63]
class-list で、ドメインロジック（ビジネスルール）の分析設計内容の可視化のリストと、それ以外の入出力処理の可視化のリストをわける。

（ドメインモデルと対象とするか、それ以外のレイヤを対象とするか）

**Comment by irof** [comment]
分離のイメージがつかめないので、「分析設計内容」と「入出力処理」のそれぞれに入るものをお聞かせください。
