### ISSUE TITLE
index.htmlを動的出力にする

### ISSUE THREAD

**Issue by irof** [dddjava/jig#656]
- [x] 出力したJIGドキュメントを出力する（現在固定なので出さないものはリンク切れとかになる）
- [ ] headヘッダのタイトルを変えられるようにする
- [ ] 読み込んだディレクトリとかクラス数とかメソッド数とか統計情報を出す
- [ ] ログも出そう

**Comment by masuda220** [comment]
- [ ] index.htmlの図にリンクを追加して、それぞれの図をブラウザで表示できるようにする
