### ISSUE TITLE
MyBatisのtypehandlerには未対応？

### ISSUE THREAD

**Issue by masuda220** [dddjava/jig#710]
## 不具合の内容
JIG実行時に以下のエラーが発生

```Caused by: java.lang.IllegalStateException: No typehandler found for property ルーム番号.value```

MyBatisにUUIDのタイプハンドラーを組み込んだ箇所と思われる
（ほかにも該当のカラムがあるが、エラーメッセージはここだけ）

## 環境
- JIGのバージョン: 2021.5.5
- 実行方法: GradlePlugin
- Javaのバージョン: 11
- OS: Windows10

**Comment by irof** [comment]
#228
