### ISSUE TITLE
出力されたhtmlファイルの左メニュー下部が見切れることがある

### ISSUE THREAD

**Issue by hc0208** [dddjava/jig#727]
[Getting-Started](https://github.com/dddjava/jig/wiki/Getting-Started) を参照し、出力されるファイルを確認していました。
domain.htmlを見ている際に、メニューを下までスクロールすると下部が見切れていることに気づきました。

![image](https://user-images.githubusercontent.com/13850867/130316094-829697b1-c7cd-4c00-bd79-b76e3860b7aa.png)

## 環境
ブラウザ： Chrome, Safari
OS: mac

**Comment by irof** [comment]
ありがとうございます！
`2021.8.3`以降で入ります。
