### ISSUE TITLE
ビジネスルール関連図で package-info.java を読み込まないようにする

### ISSUE THREAD

**Issue by tango238** [dddjava/jig#788]
再現手順を作ったらまた共有します。

**Comment by irof** [comment]
`package-info.class` とかができないと作られない認識でした。

お願いします！

**Comment by tango238** [comment]
`package-info.java` で`@ParametersAreNullableByDefault` をパッケージに対して指定しているのですが、このアノテーションつけちゃうと classファイルが生成されちゃう感じですね・・

**Comment by irof** [comment]
確認できました！ありがとうございます！！
