### ISSUE TITLE
サービスメソッドの呼び出し関係の表示

### ISSUE THREAD

**Issue by masuda220** [dddjava/Jig#80]
- [x] サービスのクラス名に、和名を併記してほしい。
- [x] メソッドの返す型を、　method() : 型名 の形式で表示してほしい。
- [ ] メソッドの引数の型名、返す型名を和名で表示したい（オプション指定？） 
- [x] イベントハンドラ（コントローラから呼ばれるメソッド）を強調表示してほしい
- [x] public / private 違いを表示したい

**Comment by masuda220** [comment]
追加
public / private 違いを表示したい

**Comment by irof** [comment]
リストにチェックボックスをつけて終わったものをチェックしていくことにします。

28408b4 でメソッドの返す型とイベントハンドラの強調表示をしました。

強調はとりあえず赤色にしていますが、どんな表現ができるかの実験を兼ねているのでコロコロ変えると思います。
