### ISSUE TITLE
markdown記述での改行

### ISSUE THREAD

**Issue by masuda220** [dddjava/jig#806]
現在は、`<br>`が必要
`<br>`を書かなくてもソースコードに書いた通りの改行を維持したい

**Comment by irof** [comment]
これはmarkdownの標準に従って改行一つでは改行しないままにします。

https://spec.commonmark.org/0.30/#hard-line-break

改行は `<br>` の他に以下の方法があります。一般的には改行2つ。

- 改行2つ
- 改行の前に `\`
- 改行の前に `  ` （スペース2つ以上）

**Comment by masuda220** [comment]
把握しました。

いちおう、IntelliJ IDEAのエディタのデフォルトの設定で起きる現象の共有

改行２つ：JavaDocの中であることを認識して、勝手に先頭に `*` を入れるので、この記法は使いにくい
改行の前にスペース二つ以上：勝手に末尾の空白を削除してしまうので、この記法は使いにくい

どちらもJIG/Markdownの問題ではないので、この件はクローズします。

**Comment by irof** [comment]
> 改行２つ：JavaDocの中であることを認識して、勝手に先頭に * を入れるので、この記法は使いにくい

一応、これは `*` 入ってても問題ないです。
