### ISSUE TITLE
ドメインモデルで、booleanを返すメソッドをリストする

### ISSUE THREAD

**Issue by masuda220** [dddjava/Jig#89]
できれば、そのメソッドの使用個所も。

狙い：
booleaを返すとと、メソッドを使った側で if文が書かれ、そこに何かしらのビジネスロジックが書かれている可能性がある。

ビジネスロジックをドメインオブジェクトに移動する候補として、検出したい。

**Comment by irof** [comment]
ビジネスルール一覧(domain.xlsx)に「真偽値を返すメソッド」シートを追加。
