### ISSUE TITLE
model の構造設計

### ISSUE THREAD

**Issue by masuda220** [dddjava/Jig#95]
(ツールの機能ではなく、現在の model の設計についてフィードバック)

現在のモデルの依存ダイヤグラムを見ると、関心事が、解析の対象と、解析の手段に偏っているように感じます。
どうやって解析しているかの手続き型プログラミングの臭いがする。

トップレベルのパッケージは、何を知りたいのかの、関心事を表現するようにしたい。

ざっくりとしたイメージですが、現在のレポートパッケージの中の XxxxReportクラスの Xxxx の部分がパッケージ図のトップレベルのパッケージ名に登場させたい感じです。

例えば

services
services.list
services.network

valueobjects 
validations
decisions
categories ( enums )
datasources

など。

**Comment by irof** [comment]
事実、解析対象や解析手段に偏っています。

reportはこねくり回してはみたのですが、「一覧」のバイアスから逃れられないので、取り扱いを考えているところです。
主な関心ごとの分析設計の観点は丁度angleに抽出しているところで、こちらをトップレベルに据えようかなと。
