### ISSUE TITLE
masterへのpushをトリガーにしてCIからSNAPSHOTを公開したい

### ISSUE THREAD

**Issue by haljik** [dddjava/jig#97]
* jig-core
* gradle-plugin

**Comment by irof** [comment]
DONE。両方CentralのSNAPSHOTに。

https://s01.oss.sonatype.org/content/repositories/snapshots/org/dddjava/jig/jig-core/
https://s01.oss.sonatype.org/content/repositories/snapshots/org/dddjava/jig/jig-gradle-plugin/

GradlePluginPortalはSNAPSHOTに対応していない模様。（ `xxx-SNAPSHOT` のバージョンでリリースはできるが、単にそのバージョン名のリリースであり、同名の上書きはできない。）

以下の形で適用可能。

```gradle
buildscript {
  repositories {
    maven {
      url 'https://s01.oss.sonatype.org/content/repositories/snapshots'
      mavenContent {
          snapshotsOnly()
      }
    }
  }
  dependencies {
    classpath 'org.dddjava.jig:jig-gradle-plugin:0.0.0-SNAPSHOT'
  }
}
apply plugin: "org.dddjava.jig-gradle-plugin"
```
