### ISSUE TITLE
メソッド和名のオーバーロードに対応する

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#98]
https://github.com/dddjava/Jig/blob/1bfc2fa0acad76a29361d6a25a36025c2e139dc5/jig-core/src/main/java/org/dddjava/jig/infrastructure/javaparser/MethodVisitor.java#L25-L37

**Comment by masuda220** [comment]
サービスクラスのメソッドは、オーバーロードはすべきではないでしょうから、問題はないでは？
